flaskenvlarge/myproject/models.py
# set up db inside the __init__.py file under myproject folder
from myproject import db


class Department(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    manager = db.relationship('Manager', backref='department', uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.manager:
            return f"Department: {self.name} has assigned manager {self.manager.name}. "
        else:
            return f"Department: {self.name} has no manager assigned yet. "


class Manager(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    # CONNECTING ONE DEPARTMENT WITH ONE MANAGER
    department_id = db.Column(db.Integer, db.ForeignKey('department.id'))

    def __init__(self, name, department_id):
        self.name = name
        self.department_id = department_id

    def __repr__(self):
        return f"Manager: {self.name} works in the Department with ID: {self.department_id}"

flaskenvlarge/myproject/departments/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of Department: ')
    submit = SubmitField('Add Department')


class DelForm(FlaskForm):
    id = IntegerField("ID of Department to remove: ")
    submit = SubmitField('Delete Department')

flaskenvlarge/myproject/managers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of Manager: ')
    dept_id = IntegerField('Department ID: ')
    submit = SubmitField('Add Manager to Department')

flaskenvlarge/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# CREATING FLASK APP
app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'

basedir = os.path.abspath(os.path.dirname(__file__))

# SQLALCHEMY CONFIGURATIONS
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# DEFINING DATABASE
db = SQLAlchemy(app)

# MIGRATING APP AND DB
Migrate(app, db)

from myproject.departments.views import department_blueprint
from myproject.managers.views import manager_blueprint

app.register_blueprint(manager_blueprint, url_prefix='/manager')
app.register_blueprint(department_blueprint, url_prefix='/department')

flaskenvlarge/myproject/departments/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Department
from myproject.departments.forms import AddForm, DelForm

department_blueprint = Blueprint('department', __name__, template_folder='templates/departments')


@department_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        # Grab info provided by user
        dept_name = form.name.data
        # Create Table instance
        new_dept = Department(dept_name)
        # DB interaction
        db.session.add(new_dept)
        db.session.commit()
        return redirect(url_for('department.list_depts'))

    else:
        return render_template('add.html', form=form)


@department_blueprint.route('/list')
def list_depts():
    all_departments = Department.query.all()
    return render_template('list.html', all_departments=all_departments)


@department_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():
    form = DelForm()
    if form.validate_on_submit():
        dept_id = form.id.data
        dept = Department.query.get(dept_id)
        db.session.delete(dept)
        db.session.commit()
        return redirect(url_for('department.list_depts'))

    else:
        return render_template('delete.html', form=form)

flaskenvlarge/myproject/managers/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Manager
from myproject.managers.forms import AddForm

manager_blueprint = Blueprint('manager', __name__, template_folder='templates/managers')


@manager_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        manager_name = form.name.data
        manager_dept_id = form.dept_id.data

        # Building Manager instance
        manager_instance = Manager(manager_name, manager_dept_id)

        # Add Manager instance to DB
        db.session.add(manager_instance)
        db.session.commit()
        return redirect(url_for('department.list_depts'))
    return render_template('add_manager.html', form=form)

flaskenvlarge/myproject/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Base Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<style>
    
    
    .container {
        width: 800px;
        margin: 100px auto;
        background-color: rgba(218, 218, 218, 0.55)
    }
    
    .nav {
        display: flex;
        justify-content: space-between;
    }
</style>
<body>
<div class="container">
    <nav class="nav">
        <a class="nav-link" href="{{url_for('index')}}">Home</a>
        <a class="nav-link" href="{{url_for('department.add')}}">Add Department</a>
        <a class="nav-link" href="{{url_for('department.delete')}}">Delete Department</a>
        <a class="nav-link" href="{{url_for('department.list_depts')}}">List Departments</a>
        <a class="nav-link" href="{{url_for('manager.add')}}">Add Manager</a>
    </nav>
</div>

{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>

flaskenvlarge/myproject/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1> Welcome to our Home Page</h1>
<p>
    Please select one of the links from the nav bar.
</p>

{% endblock %}